[[presets]]
name = "LEADHUD"
primary = 330
secondary = 260
accent = 180
negative = 359
positive = 165
partymember1 = 215
partymember2 = 150
partymember3 = 70
partymember4 = 40
partymember5 = 5
partymember6 = 300
[[presets]]
name = "ONEHUD"
primary = 30
secondary = 200
accent = 40
negative = 0
positive = 150
partymember1 = 202
partymember2 = 158
partymember3 = 45
partymember4 = 30
partymember5 = 0
partymember6 = 322
[[presets]]
name = "INSOMNIAHUD"
primary = 210
secondary = 190
accent = 25
negative = 10
positive = 150
partymember1 = 210
partymember2 = 150
partymember3 = 40
partymember4 = 30
partymember5 = 0
partymember6 = 330
