[english]
FRAG_Oobe_Description = "Thank you for downloading FRAGMENTHUD.\n\nThis HUD is work-in-progress, so things may break. Please make an issue on GitHub or ask for help on our Discord server if you encounter any issues.\n\nThis message will not show again.\n\nThank you <3\n\n-Lead"
FRAG_Oobe_HangWarn = "TF2 may hang momentarily when exiting this menu, this is normal and the game has not crashed."

FRAG_ValveRC_WarnTitle = "WARNING"
FRAG_ValveRC_WarnBody = "FRAGMENTHUD's frag_autoexec.cfg has failed to run.\n\nThis is usually because the HUD's valve.rc file was not run on startup, usually due to another mod overriding it.\n\nCustomizations will not work and are disabled, and many HUD elements will be completely broken because of this.\n\nClick the button below to learn how to fix this."
FRAG_ValveRC_WarnFix = "FIX ISSUES"

FRAG_Safemode_Warn = "Only customize when not in-game."
FRAG_Safemode_RenameWarn = "HUD folder is not renamed."

FRAG_Safemode_Supporters_Title = "CREDITS AND SUPPORTERS"
FRAG_Safemode_Supporters_Tester = "Tester ★"
FRAG_Safemode_Supporters_Contributor = "Contributor ★"
FRAG_Safemode_Supporters_Translator = "Translator ★"
FRAG_Safemode_Supporters_Donate = "DONATE"

FRAG_Safemode_Colors_Title = "COLORS"
FRAG_Safemode_Colors_Primary = "PRIMARY"
FRAG_Safemode_Colors_Accent = "ACCENT"
FRAG_Safemode_Colors_Negative = "NEGATIVE"
FRAG_Safemode_Colors_Positive = "POSITIVE"
FRAG_Safemode_Colors_Tooltip = "Restart TF2 after choosing your colors to see your changes."

FRAG_Safemode_MMenu_Title = "MAIN MENU"
FRAG_Safemode_MMenu_FList = "FRIENDS LIST"

FRAG_Safemode_Hitmarker_Title = "HITMARKER"
FRAG_Safemode_Hitmarker_Toggle = "HITMARKER TOGGLE"
FRAG_Safemode_Hitmarker_Shape = "HITMARKER SHAPE"
FRAG_Safemode_Hitmarker_Size = "HITMARKER SIZE"

FRAG_Safemode_Scoreboard_Title = "SCOREBOARD"
FRAG_Safemode_Scoreboard_Format = "FORMAT"

FRAG_Safemode_Killfeed_Title = "KILLFEED"
FRAG_Safemode_Killfeed_MaxEntries = "MAXIMUM ENTRIES"
FRAG_Safemode_Killfeed_EntryOpacity = "ENTRY OPACITY"

FRAG_Safemode_Playerclass_Title = "PLAYER CLASS"
FRAG_Safemode_3DPlayer_Toggle = "3D PLAYER MODEL"
FRAG_Safemode_2DPlayer_Toggle = "2D PLAYER IMAGE"
FRAG_Safemode_3DPlayer_Tooltip = "Use cl_hud_playerclass_use_playermodel 0/1 to swap between the 3D model and 2D image."

FRAG_Buttons_Info = "HUD Info"
FRAG_Buttons_Console = "Console"
FRAG_Buttons_DemoUI = "DemoUI"
FRAG_Buttons_FixIssues = "Attempt to fix any HUD/visual/audio issues"
FRAG_Buttons_BugReport = "Report an issue with the HUD"
FRAG_Buttons_Translate = "Help translate FRAGMENTHUD"
FRAG_Buttons_Discord = "Join our Discord server for help"
FRAG_Buttons_LeadProfile = "View developer profile"

FRAG_Etc_Small = "Small"
FRAG_Etc_Medium = "Medium"
FRAG_Etc_Large = "Large"

FRAG_CharInfo_Armory = "Catalog"

[russian]
FRAG_Oobe_Description = "Спасибо, что скачали FRAGMENTHUD.\n\nЭтот ХАД пока в разработке, поэтому некоторые вещи могут ломаться. Сообщайте о проблемах на ГитХабе или попросите помощи на нашем дискорд сервере.\n\nЭто уведомление больше не появится.\n\nСпасибо <3\n\n-Lead"
FRAG_Oobe_HangWarn = "TF2 может ненадолго зависнуть при выходе из этого меню, это нормально, игра не вылетела."

#FRAG_Safemode_Warn = "Рекомендуется применить изменения ПЕРЕД тем как заходить на сервер, это снижает шанс того, что они сломаются. После того как вы применили изменения, нужно будет перезапустить игру, чтобы цвета поменялись."
#FRAG_Safemode_RenameWarn = "Папка с ХАДом не переименована. Кастомизация не будет работать."

FRAG_Safemode_Colors_Title = "ЦВЕТА"
FRAG_Safemode_Colors_Primary = "ГЛАВНЫЙ"
FRAG_Safemode_Colors_Accent = "ВТОРОСТЕПЕННЫЙ"
FRAG_Safemode_Colors_Negative = "ОТРИЦАТЕЛЬНЫЙ"
FRAG_Safemode_Colors_Positive = "ПОЛОЖИТЕЛЬНЫЙ"

FRAG_Safemode_Hitmarker_Title = "Хитмаркер"
FRAG_Safemode_Hitmarker_Toggle = "Включить/Выключить хитмаркер"
FRAG_Safemode_Hitmarker_Shape = "Форма"
FRAG_Safemode_Hitmarker_Size = "Размер"

FRAG_Safemode_Scoreboard_Title = "Таблица счёта"
FRAG_Safemode_Scoreboard_Format = "Формат"

FRAG_Safemode_Killfeed_Title = "КИЛЛФИД"
FRAG_Safemode_Killfeed_MaxEntries = "МАКСИМУМ ОТОБРАЖАЕМЫХ СТРОК"
FRAG_Safemode_Killfeed_EntryOpacity = "ПРОЗРАЧНОСТЬ СТРОК"

FRAG_Buttons_Info = "о ХАДе"
FRAG_Buttons_Console = "Консоль"
FRAG_Buttons_DemoUI = "Демо"
FRAG_Buttons_FixIssues = "Попытаться решить проблемы с ХАДом/интерфейсом/звуком"
FRAG_Buttons_BugReport = "Сообщить об ошибке"
FRAG_Buttons_Translate = "Помочь с переводом FRAGMENTHUD"
FRAG_Buttons_Discord = "Обратиться в наш дискорд сервер за помощью"
FRAG_Buttons_LeadProfile = "Профиль создателя"

FRAG_Etc_Small = "Маленький"
FRAG_Etc_Medium = "Средний"
FRAG_Etc_Large = "Большой"

[polish]
#TRANSLATIONS BY @qareday, @nuxtjs / melody
#JEŻELI TO CZYTASZ I TEŻ JESTEŚ Z POLSKI, I COŚ WYGLĄDA NIE TAK, TO PRZETŁUMACZ TO ZA NAS, TYLKO UPEWNIJ SIĘ ZE MA SENS <3
FRAG_Oobe_Description = "Dziękuje za pobranie FRAGMENTHUD.\n\nPracuje nad tym HUDem, więc rzeczy mogą się psuć. Jeżeli znajdziesz jakieś problemy, utwórz wątek na githubie lub dołącz do naszego serwera Discord po pomoc.\n\nTa wiadomość już sie więcej nie pojawi.\n\nDziękuje <3\n\n-Lead"
FRAG_Oobe_HangWarn = "TF2 może chwilowo się zaciąć wychodząc z tego menu, jest to normalne i gra nie przestała działać."

FRAG_ValveRC_WarnTitle = "UWAGA"
FRAG_ValveRC_WarnBody = "Uruchomienie frag_autoexec.cfg FRAGMENTHUDa nie powiodło się.\n\nZazwyczaj jest to ponieważ plik valve.rc HUDa nie był uruchamiany przy włączeniu gry, zwyczajnie przez innego moda nadpisującego go.\n\nDostosowywanie nie będzie działać i jest wyłączone, i przez to wiele elementów HUDa będą kompletnie zepsute.\n\nKliknij na przycisk poniżej aby dowiedzieć się jak to naprawić."
FRAG_ValveRC_WarnFix = "NAPRAW BŁĘDY"

FRAG_Safemode_Warn = "Dostosowywuj tylko kiedy nie jesteś w grze."
FRAG_Safemode_RenameWarn = "Folder HUDa nie ma zmienionej nazwy."

FRAG_Safemode_Supporters_Title = "PODZIĘKOWANIA I SUPPORTERZY"
FRAG_Safemode_Supporters_Tester = "Tester ★"
FRAG_Safemode_Supporters_Contributor = "Kontrybutor ★"
FRAG_Safemode_Supporters_Translator = "Tłumacz ★"
FRAG_Safemode_Supporters_Donate = "PODARUJ DAROWIZNE"

FRAG_Safemode_Colors_Title = "KOLORY"
FRAG_Safemode_Colors_Primary = "GŁÓWNY"
FRAG_Safemode_Colors_Accent = "AKCENT"
FRAG_Safemode_Colors_Negative = "NEGATYWNY"
FRAG_Safemode_Colors_Positive = "POZYTYWNY"
FRAG_Safemode_Colors_Tooltip = "Zresetuj TF2 po wybraniu swojego koloru aby zobaczyć zmiany."

FRAG_Safemode_MMenu_Title = "GŁÓWNE MENU"
FRAG_Safemode_MMenu_FList = "LISTA ZNAJOMYCH"

FRAG_Safemode_Hitmarker_Title = "HITMARKER"
FRAG_Safemode_Hitmarker_Toggle = "PRZEŁĄCZNIK HITMARKERA"
FRAG_Safemode_Hitmarker_Shape = "KSZTAŁT HITMARKERA"
FRAG_Safemode_Hitmarker_Size = "WIELKOŚĆ HITMARKERA"

FRAG_Safemode_Scoreboard_Title = "TABELA WYNIKÓW"
FRAG_Safemode_Scoreboard_Format = "FORMAT"

FRAG_Safemode_Killfeed_Title = "KILLFEED"
FRAG_Safemode_Killfeed_MaxEntries = "MAKSYMALNA LICZBA WPISÓW"
FRAG_Safemode_Killfeed_EntryOpacity = "PRZEZROCZYSTOŚĆ WPISU"

FRAG_Safemode_Playerclass_Title = "KLASA GRACZA"
FRAG_Safemode_3DPlayer_Toggle = "MODEL GRACZA 3D"
FRAG_Safemode_2DPlayer_Toggle = "ZDJĘCIE GRACZA 2D"
FRAG_Safemode_3DPlayer_Tooltip = "Użyj cl_hud_playerclass_use_playermodel 0/1 aby zmieniać między modelem 3D a zdjęciem 2D."

FRAG_Buttons_Info = "Info o HUDzie"
FRAG_Buttons_Console = "Konsola"
FRAG_Buttons_DemoUI = "DemoUI"
FRAG_Buttons_FixIssues = "Spróbuj naprawić wszelkie problemy z HUDem, dzwiękiem lub widocznością"
FRAG_Buttons_BugReport = "Zgłoś błąd z HUDem"
FRAG_Buttons_Translate = "Pomóz przetłumaczyć FRAGMENTHUD"
FRAG_Buttons_Discord = "Dołącz do naszego serwera Discord jeżeli potrzebujesz pomocy"
FRAG_Buttons_LeadProfile = "Zobacz profil dewelopera"

FRAG_Etc_Small = "Małe"
FRAG_Etc_Medium = "Średnie"
FRAG_Etc_Large = "Duże"

FRAG_CharInfo_Armory = "Katalog"

[ukrainian]
#Переклад від S1LVE12R47
#Якщо в моєму перекладі щось не так, не бійтеся це виправити (й додати своє ім'я до строки вище) <3
FRAG_Oobe_Description = "Дякуємо за завантаження FRAGMENTHUD.\n\nЦей HUD в розробці тому іноді можуть траплятися помилки. Будь ласка, повідомляйте про них на GitHub або Discord.\n\nЦе повідомлення не з'явиться знову.\n\nДякую <3\n\n-Лід (-Lead)"
FRAG_Oobe_HangWarn = "TF2 може ненадовго зависнути після виходу з цього меню."

FRAG_ValveRC_WarnTitle = "УВАГА"
FRAG_ValveRC_WarnBody = "Не вдалося запустити frag_autoexec.cfg.\n\nЗазвичай, це трапляється тому що valve.rc HUD'у не запустився під час старту гри, в більшості випадків, через те що інший мод його перевизначив.\n\n Через це, налаштування не будуть працювати, а більшість елементів інтерфейсу будуть зламані.\n\nНатисніть на кнопку нижче щоб дізнатися як це виправити."
FRAG_ValveRC_WarnFix = "СПРОБУВАТИ ВИПРАВИТИ"

FRAG_Safemode_Warn = "Налаштовуйте тільки коли ви не на сервері/локальній грі."
FRAG_Safemode_RenameWarn = "Тека HUD не була перейменована."

FRAG_Safemode_Supporters_Title = "ПОДЯКИ"
FRAG_Safemode_Supporters_Tester = "Тестер ★"
FRAG_Safemode_Supporters_Contributor = "Контрибутор ★"
FRAG_Safemode_Supporters_Translator = "Перекладач ★"
FRAG_Safemode_Supporters_Donate = "ЗАДОНАТИТИ"

FRAG_Safemode_Colors_Title = "КОЛЬОРИ"
FRAG_Safemode_Colors_Primary = "ОСНОВНИЙ"
FRAG_Safemode_Colors_Accent = "ДРУГОРЯДНИЙ"
FRAG_Safemode_Colors_Negative = "НЕГАТИВНИЙ"
FRAG_Safemode_Colors_Positive = "ПОЗИТИВНИЙ"
FRAG_Safemode_Colors_Tooltip = "Перезапустіть TF2 після вибору кольорів щоб побачити ваші зміни."

FRAG_Safemode_MMenu_Title = "ГОЛОВНЕ МЕНЮ"
FRAG_Safemode_MMenu_FList = "СПИСОК ДРУЗІВ"

FRAG_Safemode_Hitmarker_Title = "ХІТМАРКЕР"
FRAG_Safemode_Hitmarker_Toggle = "ВВІМКНУТИ/ВИМКНУТИ ХІТМАРКЕР"
FRAG_Safemode_Hitmarker_Shape = "ФОРМА ХІТМАРКЕРУ"
FRAG_Safemode_Hitmarker_Size = "РОЗМІР ХІТМАРКЕРУ"

FRAG_Safemode_Scoreboard_Title = "ТАБЛО"
FRAG_Safemode_Scoreboard_Format = "ФОРМАТ"

FRAG_Safemode_Killfeed_Title = "КІЛЛФІД"
FRAG_Safemode_Killfeed_MaxEntries = "МАКСИМУМ РЯДКІВ"
FRAG_Safemode_Killfeed_EntryOpacity = "ПРОЗОРІСТЬ РЯДКІВ"

FRAG_Safemode_Playerclass_Title = "КЛАС ГРАВЦЯ"
FRAG_Safemode_3DPlayer_Toggle = "3D МОДЕЛЬ ГРАВЦЯ"
FRAG_Safemode_2DPlayer_Toggle = "2D ЗОБРАЖЕННЯ ГРАВЦЯ"
FRAG_Safemode_3DPlayer_Tooltip = "Використовуйте cl_hud_playerclass_use_playermodel 0/1 щоб перемикатися між 3D моделлю та 2D зображенням."

FRAG_Buttons_Info = "Про FRAGMENTHUD"
FRAG_Buttons_Console = "Консоль"
FRAG_Buttons_DemoUI = "DemoUI"
FRAG_Buttons_FixIssues = "Спробувати виправити проблеми з HUD/інтерфейсом/звуком"
FRAG_Buttons_BugReport = "Повідомити про помилку"
FRAG_Buttons_Translate = "Допомогти у перекладі"
FRAG_Buttons_Discord = "Зайти на сервер Discord"
FRAG_Buttons_LeadProfile = "Переглянути профіль автора"

FRAG_Etc_Small = "Малий"
FRAG_Etc_Medium = "Середній"
FRAG_Etc_Large = "Великий"

FRAG_CharInfo_Armory = "Каталог"

[spanish]
FRAG_Oobe_Description = "Gracias por descargar FRAGMENTHUD.\n\nEsta HUD esta en desarrollo, por lo que puede que algunas cosas no funcionen. Porfavor abra un ticket en la seccion Issue de GitHub o pide ayuda en nuestro servidor de Discord si llegas a encontrar algun problema.\n\nEste mensaje no se mostrara otra vez.\n\nGracias <3\n\n-Lead"
FRAG_Oobe_HangWarn = "TF2 puede que se cuelgue por un momento al salir de este menu, esto es normal y el juego no crasheara."

FRAG_ValveRC_WarnTitle = "AVISO"
FRAG_ValveRC_WarnBody = "FRAGMENTHUD's frag_autoexec.cfg no se ha ejecutado correctamente.\n\nEsto puede pasar por que el archivo valve.rc de la HUD no pudo ejecutarse desde el inicio, usualmente por que hay otro mod sobreescribiendolo.\n\nLas personalizaciones no funcionan y estan desactivadas, y bastantes elementos de la HUD estaran corruptos por culpa de esto.\n\nHaga click en el boton de abajo para saber como arreglar esto."
FRAG_ValveRC_WarnFix = "ARREGLAR PROBLEMAS"

FRAG_Safemode_Warn = "Solo personalizar cuando no esta en una partida."
FRAG_Safemode_RenameWarn = "El folder del HUD no ha sido renombrado."

FRAG_Safemode_Supporters_Title = "CREDITOS Y PARTIDARIOS"
FRAG_Safemode_Supporters_Tester = "Tester ★"
FRAG_Safemode_Supporters_Contributor = "Contribuidor ★"
FRAG_Safemode_Supporters_Translator = "Traductor ★"
FRAG_Safemode_Supporters_Donate = "HAZ UNA DONACION"

FRAG_Safemode_Colors_Title = "COLORES"
FRAG_Safemode_Colors_Primary = "PRIMARIO"
FRAG_Safemode_Colors_Accent = "CONTRASTE"
FRAG_Safemode_Colors_Negative = "NEGATIVO"
FRAG_Safemode_Colors_Positive = "POSITIVO"
FRAG_Safemode_Colors_Tooltip = "Reinicia TF2 despues de escoger tus colores para ver los cambios."

FRAG_Safemode_MMenu_Title = "MENU PRINCIPAL"
FRAG_Safemode_MMenu_FList = "AMIGOS"

FRAG_Safemode_Hitmarker_Title = "MIRA"
FRAG_Safemode_Hitmarker_Toggle = "ACTIVAR MIRA"
FRAG_Safemode_Hitmarker_Shape = "FORMA DE LA MIRA"
FRAG_Safemode_Hitmarker_Size = "TAMAÑO DE LA MIRA"

FRAG_Safemode_Scoreboard_Title = "SCOREBOARD"
FRAG_Safemode_Scoreboard_Format = "FORMATO"

FRAG_Safemode_Killfeed_Title = "KILLFEED"
FRAG_Safemode_Killfeed_MaxEntries = "MAXIMO NUMERO DE ENTRADAS"
FRAG_Safemode_Killfeed_EntryOpacity = "OPACIDAD DE LAS ENTRADAS"

FRAG_Safemode_Playerclass_Title = "CLASE DEL JUGADOR"
FRAG_Safemode_3DPlayer_Toggle = "USAR MODELO 3D PARA EL JUGADOR"
FRAG_Safemode_2DPlayer_Toggle = "USAR IMAGEN 2D PARA EL JUGADOR"
FRAG_Safemode_3DPlayer_Tooltip = "Usa cl_hud_playerclass_use_playermodel 0/1 para cambiar entre el modelo 3D y la imagen 2D."

FRAG_Buttons_Info = "Infromacion de la HUD"
FRAG_Buttons_Console = "Consola"
FRAG_Buttons_DemoUI = "DemoUI"
FRAG_Buttons_FixIssues = "Intentar arreglar problemas audiovisuales con la HUD."
FRAG_Buttons_BugReport = "Reportar un problema con la HUD"
FRAG_Buttons_Translate = "Ayudar a traducir FRAGMENTHUD"
FRAG_Buttons_Discord = "Unete a nuestro discord para ayudarte"
FRAG_Buttons_LeadProfile = "Ver perfil del desarrollador"

FRAG_Etc_Small = "Pequeño"
FRAG_Etc_Medium = "Mediano"
FRAG_Etc_Large = "Grande"

FRAG_CharInfo_Armory = "Catalogo"

[other]
FRAG_InfoCMD = "FRAGMENTHUD {0} by leadscales\nIf you have any suggestions or questions about the hud, please join our Discord server: {1}\nThank you <3"
