"Scoreboard_TimeLeft" = "%s1:%s2:%s3"
"Scoreboard_TimeLeftNoHours" = "%s1:%s2"
"Scoreboard_NoTimeLimit" = ""
"Scoreboard_TimeLeftLabel" = ""
"Scoreboard_TimeLeftNew" = "%s1:%s2:%s3"
"Scoreboard_TimeLeftNoHoursNew" = "%s1:%s2"
"Scoreboard_NoTimeLimitNew" = ""
"Scoreboard_ChangeOnRoundEndNew" = ""
"Scoreboard_Server" = "%s1"
"TF_ScoreBoard_Player" = "%s1"
"TF_ScoreBoard_Players" = "%s1"
"TF_playerid_mediccharge" = "%s1%"
"TF_playerid_mediccharge_wpn" = "%s1% (%s2)"
"TF_playerid_object_upgrading" = "%s1"
"TF_playerid_object_upgrading_level" = "(%s1) %s2"
"TF_playerid_healer" = ""
"TF_playerid_healtarget" = ""
"game_respawntime_now" = "0"
"game_respawntime_in_sec" = "1"
"game_respawntime_in_secs" = "%s1"
"game_respawntime_stalemate" = ""
"game_respawntime_next_round" = ""
"TF_Arena_NoRespawning" = ""
"TF_ClassLimitUnder" = "%s1/%s2"
"TF_Competitive_LevelTier1" = "%s1"
"TF_Competitive_Level" = "%s1+%s2"
"TF_Competitive_Placements_Multiple" = "N/A"
"TF_Competitive_Placements_Singular" = "N/A"
"TF_Casual_SelectedMaps_Plural" = "%s1"
"TF_Casual_SelectedMaps_Singular" = "%s1"
"Gametype_HalloweenFeatured" = "Slop"
"Gametype_SmissmasFeatured" = "Slop"
"Gametype_SummerFeatured" = "Slop"
